### ISSUE TITLE
make disaggregate_soc a bool not a symbol

### ISSUE THREAD

**Issue by chriscoey** [mlubin/Pajarito.jl#90] opened 2016-04-18 04:00 UTC
and rename it if it doesn't make sense. in the original code, it seems a name like disagg_soc_if_conic would make more sense, if I understood it correctly

**Comment by emreyamangil** [comment] 2016-04-18 04:23
We did it this way for default value.

**Comment by emreyamangil** [comment] 2016-04-18 04:27
its actually neat, user inputs a bool but it is cast into a symbol for having a third state that is default.

**Comment by emreyamangil** [comment] 2016-04-18 13:34
Closing this issue because this was intended!

**Closed by emreyamangil** 2016-04-18 13:34 UTC

**Comment by emreyamangil** [comment] 2016-04-18 14:58
Made it an enum, lemme know if this is better Chris!

**Comment by emreyamangil** [comment] 2016-04-18 14:58
(But the user is interacting with a bool)
